apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claims
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/<you>/crossplane-gitops-aws.git
    targetRevision: main
    path: claims
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
