apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.storage.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: storage.example.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: s3bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  region: us-east-1
            patches:
              - fromFieldPath: "spec.parameters.region"
                toFieldPath: "spec.forProvider.region"
